name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [17]
    steps:
      # Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # Устанавливаем JDK
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      # Сборка проекта
      - name: Build project
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ./gradlew.bat -B --no-daemon build
          else
            ./gradlew -B --no-daemon build
          fi

      # Запуск тестов
      - name: Run tests
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            ./gradlew.bat -B --no-daemon test
          else
            ./gradlew -B --no-daemon test
          fi

      # Публикация результатов тестирования с уникальным именем для каждой ОС
      - name: Publish test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ runner.os }}
          path: build/test-results/test/

  test-deploy:
    name: Test Deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy output
        run: |
          echo "Calc proj deploy"